// Bundles the tested account calculations (src/demo/accounts.ts and the core it uses) into demo/index.html,
// so the frozen promotional demo shows exactly what the app computes. Run after changing src/core or src/demo:
//   npm run demo:build
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("../", import.meta.url));
const BEGIN = "/* BEGIN accounts-bundle (generated by scripts/build-demo.mjs; do not edit) */";
const END = "/* END accounts-bundle */";

export async function bundle() {
  const out = await build({
    entryPoints: [root + "src/demo/demo-entry.ts"],
    bundle: true,
    write: false,
    format: "iife",
    globalName: "SadafAccounts",
    target: "es2019",
    minify: true,
    legalComments: "none",
    alias: { "@": root + "src" },
  });
  // The bundle is inlined in a <script> block, so a literal closing tag must never appear in it.
  return out.outputFiles[0].text.trim().replace(/<\/script/gi, "<\\/script");
}

export function embed(html, code) {
  // esbuild's IIFE declares `var SadafAccounts`; wrap it so only window.SadafAccounts leaks into the page.
  const block = `${BEGIN}\nwindow.SadafAccounts=(()=>{${code}\nreturn SadafAccounts;})();\n${END}`;
  const re = new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&")}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&")}`);
  if (!re.test(html)) throw new Error("accounts-bundle markers not found in demo/index.html");
  return html.replace(re, () => block);
}

if (process.argv[1]?.endsWith("build-demo.mjs")) {
  const path = root + "demo/index.html";
  const html = readFileSync(path, "utf8");
  const next = embed(html, await bundle());
  if (next !== html) writeFileSync(path, next);
  console.log(next === html ? "demo bundle already up to date" : "demo bundle updated");
}
